import type { Metadata } from "next";
import "./globals.css";
import { heading, inter } from "./fonts";
import Image from "next/image";
import Link from "next/link";
import { getSession } from "@/lib/session";

export const metadata: Metadata = {
  title: "Handcrafted Haven",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();
  const isLoggedIn = session?.userId !== undefined;

  return (
    <html lang="en">
      <body
        className={`min-h-full flex flex-col ${inter.className} antialiased`}
      >
        <header className="flex items-center justify-between gap-6 p-4">
          <Link
            href="/"
            className="logo flex items-center gap-3 transition hover:opacity-80"
          >
            <Image
              className="h-auto"
              alt="logo"
              src="/images/logo.webp"
              width={64}
              height={64}
              loading="eager"
            />
            <span
              className={`title text-[32px] font-black text-[#1B5E20] ${heading.className}`}
            >
              Handcrafted Haven
            </span>
          </Link>

          <nav className="rounded-[5px] border border-[#A5D6A7] bg-[#A5D6A7]/10 px-4 py-3">
            <ul className="flex items-center gap-4 text-sm font-medium text-slate-950">
              <li>
                <Link
                  href="/artists"
                  className="font-sans font-semibold text-slate-950"
                >
                  Artists
                </Link>
              </li>
              <li>
                <Link
                  href="/customer"
                  className="font-sans font-semibold text-slate-950"
                >
                  Product Listings
                </Link>
              </li>
              <li>
                <Link
                  href="/seller"
                  className="font-sans font-semibold text-slate-950"
                >
                  Seller Profile
                </Link>
              </li>
              <li>
                {(isLoggedIn && (
                  <Link
                    href="/logout"
                    className="font-sans font-semibold text-slate-950"
                  >
                    Logout
                  </Link>
                )) || (
                  <Link
                    href="/login"
                    className="font-sans font-semibold text-slate-950"
                  >
                    Login
                  </Link>
                )}
              </li>
            </ul>
          </nav>
        </header>

        {children}

        <footer></footer>
      </body>
    </html>
  );
}
