import type { Metadata } from "next";
import "./globals.css";
import { inter } from "./fonts";
import Image from "next/image";
import Link from "next/link";
import { AuthProvider } from "../lib/auth/auth-context";

export const metadata: Metadata = {
  title: "Handcrafted Haven",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`min-h-full flex flex-col ${inter.className} antialiased`}
      >
        <AuthProvider>
          <header>
            <div className="logo">
              <Image
                className="h-auto"
                alt="logo"
                src="/images/logo.webp"
                width={64}
                height={64}
                loading="eager"
              />
              <span className="title">Handcrafted Haven</span>
            </div>

            <nav>
              <ul>
                <li>
                  <Link href="#">Artists</Link>
                </li>

                <li>
                  <Link href="#">Product Listings</Link>
                </li>

                <li>
                  <Link href="#">Login</Link>
                </li>
              </ul>
            </nav>
          </header>

          {children}

          <footer></footer>
        </AuthProvider>
      </body>
    </html>
  );
}
